export const SAVE_CSV_DATA = "SAVE_CSV_DATA";
export const CHOOSE_DATA_GET_OPTION_DROPDOWN = "CHOOSE_DATA_GET_OPTION_DROPDOWN";
export const DATA_IS_UPLOADED = "DATA_IS_UPLOADED"
// export const CHOOSE_GET_FROM_TOUCH_OPTION_DROPDOWN = "CHOOSE_GET_FROM_TOUCH_OPTION_DROPDOWN";