export const SAVE_CSV_DATA = "SAVE_CSV_DATA";
export const SAVE_CSV_DATA_FOR_FILTERING = "SAVE_CSV_DATA_FOR_FILTERING";
export const CHOOSE_DATA_GET_OPTION_DROPDOWN = "CHOOSE_DATA_GET_OPTION_DROPDOWN";
export const DATA_IS_UPLOADED = "DATA_IS_UPLOADED"
export const SHOW_RAPHS_BUTTON_IS_PRESSED = "SHOW_RAPHS_BUTTON_IS_PRESSED"
export const CHOOSE_DATA_GET_CSV_OPTION_DROPDOWN = "CHOOSE_DATA_GET_CSV_OPTION_DROPDOWN"
export const CHOOSE_GET_FROM_TOUCH_OPTION_DROPDOWN = "CHOOSE_GET_FROM_TOUCH_OPTION_DROPDOWN";